name: Deploy Tecxell26 to Production

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy existing .env files
        run: |
          # Copy backend .env
          cp /home/mediaclub-backend2/Tecxell26/Server/.env ./Server/.env
          
          # Copy frontend .env
          cp /home/mediaclub-backend2/Tecxell26/Client/.env ./Client/.env

      - name: Deploy with Docker Compose
        run: |
          # Build sequentially to prevent the self-hosted runner from running out of memory
          docker compose build backend
          docker compose build frontend
          
          # Start the services
          docker compose up -d
          
          docker image prune -f
